# Generated by Django 4.2.25 on 2025-11-10 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='activo',
        ),
    ]
